public class AccountHandler{
    public static Account insertNewAccount(String accName){
     if(String.isBlank(accName)){
     return null;
     }else{
     Account acc = new Account(Name=accName);
     insert acc;
     return acc;
     system.debug('hello');
     system.debug('find');
     system.debug('find');
     system.debug('find');
     system.debug('find');
     system.debug('find');
     system.debug('hello');
     system.debug('hello');
     system.debug('hello');
     system.debug('hello');
     system.debug('hello');
     if(String.isBlank(accName)){
         
     system.debug('hello');
     system.debug('hello');
     }




     }
    }


}