public with sharing class Demo {
    public Demo() {

        System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');System.debug('Hellp');
          System.debug('Hellp');
          System.debug('Hellp');

        system.debug('Hello Bla bla');
         system.debug('Hello Bla bla'); system.debug('Hello Bla bla');
         system.debug('Hello Bla bla'); system.debug('Hello Bla bla');
        
         System.debug('Hellp1');
          System.debug('Hellp1');
    }
}
